build_docker_image:
  stage: build
  image: quay.io/buildah/stable
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
    BUILDAH_ISOLATION: chroot
  before_script:
    - export REGISTRY_AUTH_FILE=$HOME/auth.json
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - buildah manifest create multiarch
    - buildah bud --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" --manifest multiarch --arch amd64 $CI_PROJECT_DIR
    - buildah bud --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" --manifest multiarch --arch arm64 $CI_PROJECT_DIR
    - buildah manifest push --all multiarch "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG

deploy_prod:
  stage: deploy
  needs:
    - build_docker_image
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - sed -i "s/VERSION_TAG/$CI_COMMIT_TAG/g" $CI_PROJECT_DIR/kubernetes/daemonset.yaml
    - kubectl config get-contexts
    - kubectl config use-context catmunch-networking/dns-whois-server:production
    - kubectl apply -f $CI_PROJECT_DIR/kubernetes/daemonset.yaml
  rules:
    - when: manual
      if: $CI_COMMIT_TAG
