apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dns-whois-server
  namespace: catmunchnet
  labels:
    app.kubernetes.io/name: catmunchnet-dns-whois-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: catmunchnet-dns-whois-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: catmunchnet-dns-whois-server
    spec:
      tolerations:
        # these tolerations are to have the daemonset runnable on control plane nodes
        # remove them if your control plane nodes should not run pods
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: dns-whois-server
          image: registry.starcatmeow.cn/catmunch-networking/dns-whois-server:VERSION_TAG
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 32Mi
          env:
            - name: GIT_REPO
              valueFrom:
                secretKeyRef:
                  name: catmunchnet-registry
                  key: git_repo
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 43
              name: whois
      terminationGracePeriodSeconds: 1