apiVersion: v1
kind: Service
metadata:
  name: dns-whois-server
  namespace: catmunchnet
  annotations:
    metallb.universe.tf/address-pool: catmunchnet-anycast-dns
spec:
  selector:
    app.kubernetes.io/name: catmunchnet-dns-whois-server
  ports:
    - protocol: UDP
      port: 53
      targetPort: dns
      name: dns
    - protocol: TCP
      port: 43
      targetPort: whois
      name: whois
  type: LoadBalancer
  loadBalancerIP: 10.53.53.53
