name: Build image

on:
  push:
    branches:
      - main
    tags:
      - v*

permissions:
  packages: write

jobs:
  build-amd64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build amd64
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/catmunch/catmunchnet-dns-whois-server:${{ github.sha }}-arm64
  build-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build arm64
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          file: Dockerfile.arm64
          push: true
          tags: |
            ghcr.io/catmunch/catmunchnet-dns-whois-server:${{ github.sha }}-arm64
          labels: ${{ steps.meta.outputs.labels }}
  create-manifests:
    runs-on: ubuntu-24.04
    needs: [build-amd64, build-arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/catmunch/catmunchnet-dns-whois-server
      - name: Create SHA manifest and push
        run: |
          docker manifest create \
            ghcr.io/catmunch/catmunchnet-dns-whois-server:${{ github.sha }} \
            --amend ghcr.io/catmunch/catmunchnet-dns-whois-server:${{ github.sha }}-arm64 \
            --amend ghcr.io/catmunch/catmunchnet-dns-whois-server:${{ github.sha }}-amd64
          docker manifest push ghcr.io/catmunch/catmunchnet-dns-whois-server:${{ github.sha }}
      - name: Create latest manifest and push
        run: |
          docker manifest create \
            ghcr.io/catmunch/catmunchnet-dns-whois-server:latest \
            --amend ghcr.io/catmunch/catmunchnet-dns-whois-server:${{ github.sha }}-arm64 \
            --amend ghcr.io/catmunch/catmunchnet-dns-whois-server:${{ github.sha }}-amd64
          docker manifest push ghcr.io/catmunch/catmunchnet-dns-whois-server:latest
      
